import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Patient } from '@/types';
import { Head, Link, useForm } from '@inertiajs/react';

export default function Show({ patient }: { patient: Patient }) {
    const { delete: destroy, processing } = useForm();
    const remove = () => { if (window.confirm('Archivar este paciente?')) destroy(route('patients.destroy', patient.id)); };

    return <AuthenticatedLayout header={<h2 className="text-xl font-semibold leading-tight text-gray-800">Datos del paciente</h2>}><Head title={`${patient.first_name} ${patient.last_name}`} /><div className="py-12"><div className="mx-auto max-w-4xl space-y-6 sm:px-6 lg:px-8"><div className="flex justify-between"><div><h1 className="text-2xl font-semibold text-gray-900">{patient.first_name} {patient.last_name}</h1><p className="text-sm text-gray-500">Paciente #{patient.id}</p></div><div className="flex gap-3"><Link href={route('patients.edit', patient.id)} className="rounded-md bg-indigo-600 px-4 py-2 text-xs font-semibold uppercase tracking-widest text-white">Editar</Link><button onClick={remove} disabled={processing} className="rounded-md bg-red-600 px-4 py-2 text-xs font-semibold uppercase tracking-widest text-white disabled:opacity-50">Archivar</button></div></div><div className="grid gap-6 bg-white p-6 shadow-sm sm:grid-cols-2 sm:rounded-lg"><div><dt className="text-sm text-gray-500">Fecha de nacimiento</dt><dd className="mt-1 text-gray-900">{patient.date_of_birth ?? '-'}</dd></div><div><dt className="text-sm text-gray-500">Sexo</dt><dd className="mt-1 text-gray-900">{patient.gender ?? '-'}</dd></div><div><dt className="text-sm text-gray-500">Telefono</dt><dd className="mt-1 text-gray-900">{patient.phone ?? '-'}</dd></div><div><dt className="text-sm text-gray-500">Correo electronico</dt><dd className="mt-1 text-gray-900">{patient.email ?? '-'}</dd></div><div className="sm:col-span-2"><dt className="text-sm text-gray-500">Direccion</dt><dd className="mt-1 whitespace-pre-line text-gray-900">{patient.address ?? '-'}</dd></div><div className="sm:col-span-2"><dt className="text-sm text-gray-500">Notas medicas</dt><dd className="mt-1 whitespace-pre-line text-gray-900">{patient.medical_notes ?? '-'}</dd></div></div><Link href={route('patients.index')} className="inline-block text-sm text-gray-600 underline">Volver a pacientes</Link></div></div></AuthenticatedLayout>;
}
