import { ClinicalHistory, PageProps, Patient } from '@/types';
import { Head, usePage } from '@inertiajs/react';

type Props = { patient: Patient; clinicalHistory: ClinicalHistory; responsibleDentist: { id: number; name: string; license_number: string | null } | null };

const labels: Record<string, string> = {
    father_alive: 'Padre con vida', father_conditions: 'Enfermedades del padre', mother_alive: 'Madre con vida', mother_conditions: 'Enfermedades de la madre', has_siblings: 'Tiene hermanos', siblings_health: 'Salud de hermanos',
    medications: 'Medicamentos habituales', medications_last_five_years: 'Medicamentos en últimos cinco años', sports: 'Deportes', exercise_discomfort: 'Malestar al hacer deporte', drug_allergy: 'Alergia a medicamentos', anesthesia_allergy: 'Alergia a anestesia', penicillin_allergy: 'Alergia a penicilina', poor_healing_or_bleeding: 'Sangrado o cicatrización', collagen_disorder: 'Colágeno o hiperlaxitud', rheumatic_fever: 'Fiebre reumática', diabetes: 'Diabetes', diabetes_control: 'Control de diabetes', heart_condition: 'Problema cardíaco', anticoagulants: 'Aspirina o anticoagulantes', high_blood_pressure: 'Presión alta', chagas: 'Chagas', kidney_condition: 'Problemas renales', gastric_ulcer: 'Úlcera gástrica', hepatitis: 'Hepatitis', hepatitis_type: 'Tipo de hepatitis', liver_condition: 'Problema hepático', seizures: 'Convulsiones', epilepsy: 'Epilepsia', sti_history: 'Sífilis o gonorrea', other_contagious_disease: 'Otra enfermedad contagiosa', transfusions: 'Transfusiones', previous_surgery: 'Operaciones', operation_when: 'Fecha de operación', respiratory_condition: 'Problema respiratorio', smokes: 'Fuma', pregnant: 'Embarazo', pregnancy_months: 'Meses de embarazo', other_medical_recommendation: 'Recomendación médica', homeopathic_treatment: 'Homeopatía u otros tratamientos', clinician_name: 'Médico clínico', referral_clinic: 'Clínica de derivación',
    reason: 'Motivo de consulta', previous_professional: 'Consulta con otro profesional', took_medication: 'Tomó medicamentos', medication_names: 'Medicamentos', medication_since: 'Desde cuándo', treatment_result: 'Obtuvo resultados', had_pain: 'Tuvo dolor', pain_intensity: 'Intensidad', pain_duration: 'Duración', pain_origin: 'Origen', pain_trigger: 'Frío/calor', pain_location: 'Localización', pain_radiation: 'Irradiación', pain_relief: 'Alivio', tooth_trauma: 'Golpe dental', trauma_when: 'Cuándo', trauma_details: 'Cómo ocurrió', fractured_tooth: 'Diente fracturado', fracture_details: 'Diente', fracture_treatment: 'Tratamiento', speaking_difficulty: 'Dificultad para hablar', chewing_difficulty: 'Dificultad para masticar', opening_difficulty: 'Dificultad para abrir la boca', swallowing_difficulty: 'Dificultad para tragar',
    lips_present: 'Labios anormales', lips_details: 'Detalle de labios', tongue_present: 'Lengua anormal', tongue_details: 'Detalle de lengua', palate_present: 'Paladar anormal', palate_details: 'Detalle de paladar', floor_of_mouth_present: 'Piso de boca anormal', floor_of_mouth_details: 'Detalle de piso de boca', cheeks_present: 'Carrillos anormales', cheeks_details: 'Detalle de carrillos', ridges_present: 'Rebordes anormales', ridges_details: 'Detalle de rebordes', spots_present: 'Manchas', swelling_present: 'Abultamientos', ulcers_present: 'Ulceraciones', blisters_present: 'Ampollas', lesion_details: 'Lesiones', gum_bleeding: 'Sangrado gingival', gum_bleeding_when: 'Cuándo sangran', pus: 'Pus', pus_location: 'Ubicación de pus', tooth_mobility: 'Movilidad dental', bite_high: 'Dientes altos al morder', bite_high_details: 'Detalle de mordida', facial_swelling: 'Cara hinchada', swelling_treatment: 'Hielo/calor/otros', daily_sugar_moments: 'Momentos de azúcar diario',
};

function Value({ label, value }: { label: string; value: unknown }) {
    if (value === null || value === undefined || value === '') return null;
    const readable = value === 'yes' ? 'Sí' : value === 'no' ? 'No' : value === 'unknown' ? 'No sabe / no registrado' : String(value);
    return <div className="print-field"><strong>{label}: </strong><span>{readable}</span></div>;
}

function Section({ title, data }: { title: string; data: Record<string, unknown> }) {
    return <section className="print-section"><h2>{title}</h2><div className="print-grid">{Object.entries(data ?? {}).map(([key, value]) => <Value key={key} label={labels[key] ?? key.replaceAll('_', ' ')} value={value} />)}</div></section>;
}

export default function Print({ patient, clinicalHistory, responsibleDentist }: Props) {
    const { clinic } = usePage<PageProps>().props;
    const intake = clinicalHistory.intake_responses ?? {};
    const assessment = clinicalHistory.assessment_data ?? {};

    return <><Head title={`Historia clínica imprimible · ${patient.first_name} ${patient.last_name}`} /><style>{`
        @page { size: A4; margin: 12mm; }
        @media print { body { background: white !important; } .print-hide { display: none !important; } .print-page { box-shadow: none !important; margin: 0 !important; max-width: none !important; } .print-section { break-inside: avoid; } }
        .print-page { font-family: Arial, sans-serif; color: #111827; } .print-section { margin-top: 18px; border-top: 1px solid #94a3b8; padding-top: 10px; } .print-section h2 { font-size: 15px; font-weight: 700; margin-bottom: 8px; } .print-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 5px 18px; } .print-field { font-size: 11px; white-space: pre-wrap; } .print-signatures { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 28px; margin-top: 56px; text-align: center; font-size: 11px; } .print-signatures div { border-top: 1px solid #111827; padding-top: 6px; }
    `}</style><main className="print-page mx-auto max-w-5xl bg-white p-6 sm:p-10"><div className="print-hide mb-6 flex justify-between"><button type="button" onClick={() => window.print()} className="rounded-xl bg-blue-700 px-5 py-3 font-semibold text-white">Imprimir</button><button type="button" onClick={() => window.history.back()} className="rounded-xl border border-slate-300 px-5 py-3 font-semibold">Volver</button></div><header className="text-center"><p className="text-sm font-semibold uppercase tracking-widest">{clinic['clinic.name']}</p><h1 className="mt-2 text-2xl font-bold">HISTORIA CLÍNICA ODONTOLÓGICA</h1><p className="mt-1 text-sm">Fecha de impresión: {new Date().toLocaleDateString()}</p></header>
        <section className="print-section"><h2>Datos generales</h2><div className="print-grid">{Object.entries({ Paciente: `${patient.first_name} ${patient.last_name}`, 'N.º de expediente': patient.id, 'Fecha de nacimiento': patient.date_of_birth, Edad: patient.date_of_birth ? `${Math.floor((Date.now() - new Date(`${patient.date_of_birth}T00:00:00`).getTime()) / 31557600000)} años` : null, Documento: `${patient.document_type ?? ''} ${patient.document_number ?? ''}`, 'Obra social': patient.insurance_provider, Afiliación: patient.insurance_member_number, 'Estado civil': patient.marital_status, Nacionalidad: patient.nationality, Teléfono: patient.phone, Celular: patient.mobile_phone, Correo: patient.email, Domicilio: patient.address, Profesión: patient.occupation, Titular: patient.insurance_holder, 'Lugar de trabajo': patient.workplace, Jerarquía: patient.job_title }).map(([label, value]) => <Value key={label} label={label} value={value} />)}</div></section>
        {Object.entries(intake).filter(([, data]) => data && typeof data === 'object').map(([section, data]) => <Section key={section} title={({ family: 'Antecedentes familiares', health: 'Cuestionario de salud general', dental: 'Historia odontológica', oral: 'Síntomas y observaciones bucales' } as Record<string, string>)[section] ?? section} data={data as Record<string, unknown>} />)}
        <section className="print-section"><h2>Evaluación profesional</h2><div className="print-grid">{Object.entries({ 'Odontólogo responsable': responsibleDentist?.name, 'Matrícula profesional': assessment.license_number ?? responsibleDentist?.license_number, Lugar: assessment.office_location, 'Motivo de consulta': assessment.consultation_reason, 'Padecimiento actual': assessment.current_condition, 'Signos vitales': JSON.stringify(assessment.vital_signs ?? {}), 'Exploración extraoral': assessment.extraoral_exam, 'Exploración intraoral': assessment.intraoral_exam, 'Tejidos blandos': assessment.soft_tissue_findings, 'Sangrado gingival': assessment.gingival_bleeding, Supuración: assessment.pus, 'Movilidad dental': assessment.tooth_mobility, Oclusión: assessment.occlusal_discomfort, 'Inflamación facial': assessment.facial_swelling, 'Índice de placa': assessment.plaque_index, 'Higiene bucal': assessment.oral_hygiene, Sarro: assessment.calculus, 'Enfermedad periodontal': assessment.periodontal_disease, Alergias: clinicalHistory.allergies, 'Condiciones médicas': clinicalHistory.medical_conditions, Medicamentos: clinicalHistory.current_medications, 'Antecedentes quirúrgicos': clinicalHistory.surgical_history, 'Antecedentes familiares': clinicalHistory.family_history, Hábitos: clinicalHistory.habits, 'Diagnóstico presuntivo': assessment.diagnosis, Pronóstico: assessment.prognosis, 'Plan de tratamiento': assessment.treatment_plan_notes, Observaciones: assessment.observations, 'Anexo número': assessment.annex_number, 'Fecha del plan': assessment.treatment_plan_date }).map(([label, value]) => <Value key={label} label={label} value={value} />)}</div></section>
        <section className="print-section"><h2>Consentimiento informado</h2><p className="text-xs leading-relaxed">He comprendido las explicaciones que se me han facilitado en lenguaje claro y sencillo, he podido realizar observaciones y se me han aclarado mis dudas. Estoy de acuerdo con el tratamiento propuesto para rehabilitar mi salud bucodental.</p><p className="mt-3 text-xs">El/la que suscribe declara que otorga su consentimiento para realizar el tratamiento necesario.</p><div className="print-signatures"><div>Firma del paciente o tutor</div><div>Aclaración y parentesco</div><div>Documento</div></div><div className="print-signatures"><div>Firma del odontólogo</div><div>Nombre del odontólogo</div><div>N.º de matrícula</div></div></section>
    </main></>;
}
