import InputError from '@/Components/InputError';
import InputLabel from '@/Components/InputLabel';
import PrimaryButton from '@/Components/PrimaryButton';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Branding, PageProps } from '@/types';
import { Head, useForm } from '@inertiajs/react';
import { ChangeEvent, FormEvent } from 'react';

export default function Edit({ branding }: PageProps<{ branding: Branding }>) {
    const form = useForm<{ name: string; variant: Branding['variant']; theme: Branding['theme']; logo: File | null; icon: File | null }>({ name: branding.name, variant: branding.variant, theme: branding.theme, logo: null, icon: null });
    const setFile = (field: 'logo' | 'icon') => (event: ChangeEvent<HTMLInputElement>) => form.setData(field, event.target.files?.[0] ?? null);
    const submit = (event: FormEvent) => { event.preventDefault(); form.patch(route('admin.branding.update'), { forceFormData: true, preserveScroll: true }); };

    return <AuthenticatedLayout header={<div><p className="text-sm font-medium text-teal-600">Configuracion del sistema</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-slate-900">Marca y apariencia</h1></div>}><Head title="Marca y apariencia" /><div className="min-h-[calc(100vh-5rem)] bg-slate-50 px-4 py-8 sm:px-6 lg:px-8"><div className="mx-auto max-w-3xl"><form onSubmit={submit} className="space-y-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div><h2 className="text-lg font-semibold text-slate-900">Identidad</h2><p className="mt-1 text-sm text-slate-500">Esta informacion aparece en el espacio de trabajo y el acceso.</p></div><div><InputLabel htmlFor="name" value="Nombre de la clinica" /><input id="name" value={form.data.name} onChange={(event) => form.setData('name', event.target.value)} className="mt-2 block w-full rounded-xl border-slate-300 shadow-sm focus:border-teal-500 focus:ring-teal-500" /><InputError message={form.errors.name} className="mt-2" /></div><div className="grid gap-5 sm:grid-cols-2"><div><InputLabel htmlFor="variant" value="Estilo visual" /><select id="variant" value={form.data.variant} onChange={(event) => form.setData('variant', event.target.value as Branding['variant'])} className="mt-2 block w-full rounded-xl border-slate-300 shadow-sm"><option value="clinical">Clinico</option><option value="modern">Moderno</option><option value="minimal">Minimalista</option></select></div><div><InputLabel htmlFor="theme" value="Tema" /><select id="theme" value={form.data.theme} onChange={(event) => form.setData('theme', event.target.value as Branding['theme'])} className="mt-2 block w-full rounded-xl border-slate-300 shadow-sm"><option value="light">Claro</option><option value="dark">Oscuro</option><option value="system">Sistema</option></select></div></div><div className="grid gap-5 sm:grid-cols-2"><div><InputLabel htmlFor="logo" value="Logotipo" /><input id="logo" type="file" accept=".jpg,.jpeg,.png,.webp,.svg" onChange={setFile('logo')} className="mt-2 block w-full text-sm text-slate-500" /><p className="mt-1 text-xs text-slate-400">PNG, JPG, WebP o SVG. Maximo 4 MB.</p><InputError message={form.errors.logo} className="mt-2" /></div><div><InputLabel htmlFor="icon" value="Icono" /><input id="icon" type="file" accept=".jpg,.jpeg,.png,.webp,.svg" onChange={setFile('icon')} className="mt-2 block w-full text-sm text-slate-500" /><p className="mt-1 text-xs text-slate-400">Se usa en el navegador y accesos directos.</p><InputError message={form.errors.icon} className="mt-2" /></div></div><PrimaryButton disabled={form.processing}>Guardar apariencia</PrimaryButton></form></div></div></AuthenticatedLayout>;
}
